[package]
name = "wit-bindgen-cli"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = ["crates/test-rust-wasm", "crates/wit-component"]
resolver = "2"

[[bin]]
name = "wit-bindgen"
test = false

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
wit-bindgen-gen-core = { path = 'crates/gen-core' }
wit-bindgen-gen-rust-wasm = { path = 'crates/gen-rust-wasm', features = [
  'structopt',
] }
wit-bindgen-gen-wasmtime = { path = 'crates/gen-wasmtime', features = [
  'structopt',
] }
wit-bindgen-gen-markdown = { path = 'crates/gen-markdown', features = [
  'structopt',
] }

# Compiling `spidermonkey.wasm` takes way too long without this.
[profile.dev.package.cranelift-codegen]
debug-assertions = false
opt-level = 2
